# Generated by Django 2.0.3 on 2018-09-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/avatars/tx.png', upload_to='avatars/'),
        ),
    ]
